### ISSUE TITLE
Doesn't seem to work on Windows at all.

### ISSUE THREAD

**Issue by helgridly** [octalmage/HotGifs#25]
At least not for me. I download the Windows release, extracted it, and ran `Hot Gifs.exe`. Task Manager shows three instances of the executable running, one of them repeatedly climbing to around 200MB memory usage and then dropping back to 3MB or so. Ctrl + Alt + G does nothing and I see no tray icon.

**Comment by octalmage** [comment]
Hmm that's odd! I'll try to run some tests tonight. On Mac the hotkey is command+alt+g, could you try win+alt+g? 

Thanks!

**Comment by helgridly** [comment]
I tried Win+Alt+G, Ctrl+Alt+G, and Ctrl+Win+G. Nada.

**Comment by octalmage** [comment]
This has been fixed, the build has been updated!

**Comment by octalmage** [comment]
Make sure the previous Hot Gifs process isn't running.

**Comment by helgridly** [comment]
Confirmed working. Thanks!
