### ISSUE TITLE
Make window movable

### ISSUE THREAD

**Issue by qwixilver** [octalmage/HotGifs#5]
On rare occasion, the window position seems to shift on my mulit monitor setup (see screenshot)

![screenshot](https://api.monosnap.com/image/download?id=kMRwgwmQCC1SiI1ywvfiBBp6inBMvg)

you can see the window appears slightly off of one monitor, but doesn't span the displays. 

These things happen, but it would be great if I could reposition the window when they do.

**Comment by octalmage** [comment]
Hmm I don't use a multi-monitor setup often so I haven't encountered this. 

How often would you say this happens? Do you have an idea why or when? 

It wouldn't be hard to make the window draggable if that would help! Do you want to move it so you can see the full dialog?

**Comment by qwixilver** [comment]
Its happened a couple of times I'm sure, but I only recently discovered
it... When it's happened in the past, it just appeared to me that the
window didn't open at all (since I wasn't expecting it to appear in such a
strange place), so unfortunately I have no idea what causes it

On Wed, Jan 21, 2015 at 10:14 PM, Jason Stallings <notifications@github.com>
wrote:

> Hmm I don't use a multi-monitor setup often so I haven't encountered this.
>
> How often would you say this happens? Do you have an idea why or when?
>
> It wouldn't be hard to make the window draggable if that would help! Do
> you want to move it so you can see the full dialog?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/octalmage/HotGifs/issues/5#issuecomment-70969114>.
>



-- 
The first computer bug was actually a moth trapped in a relay at Harvard's
Computation Laboratory in 1947. The moth is still trapped in the lab's log
book, with the words "First actual case of bug being found."

visit my website:
http://dubstepoftheday.com

**Comment by octalmage** [comment]
There's no reason the window shouldn't be draggable, so I'll make it happen!

**Comment by octalmage** [comment]
Done! You can click anywhere and drag to move the window, and double clicking the window will re-center it.
